[package]
name = "api"
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["serde", "v4"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
thiserror = "2"
regress = "0.12"

[build-dependencies]
typify = "0.8"
schemars = "0.8"
serde_json = "1"
syn = { version = "3", features = ["full"] }
prettyplease = "0.3"
