[package]
name = "app"
edition.workspace = true
license.workspace = true

[dependencies]
gpui-kit.workspace = true
api = { path = "../api" }
core = { path = "../core" }
platform = { path = "../platform" }
uuid = { version = "1", features = ["serde", "v4"] }
serde_json = "1"

[[bin]]
name = "koyori"
path = "src/main.rs"
